- name: Collect rx_errs from all servers
  hosts: cacerror_servers
  ignore_unreachable: true
  gather_facts: no
  serial: 1

  tasks:
    - name: Run awk on /proc/net/dev
      shell: |
        awk 'NR==2{print "iface rx_bytes rx_packets rx_errs rx_drop rx_fifo rx_frame rx_compressed rx_multicast"}
             NR>2{gsub(":","",$1); print $1,$2,$3,$4,$5,$6,$7,$8,$9}' /proc/net/dev | column -t
      register: net_stats

    - name: Append results to single file on control node
      lineinfile:
        path: net_stats_all.txt
        insertafter: EOF
        line: |
          =========================================
          Host: {{ inventory_hostname }}
          IP: {{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}
          {{ net_stats.stdout | default('UNREACHABLE') }}
      delegate_to: localhost

